---
# https://pre-commit.com

- id: markdown-toc
  name: markdown-toc (DEPRECATED, switch to github:jmknoble/mark-toc)
  description: This hook generates tables of contents in Markdown files.
  entry: markdown-toc --pre-commit
  language: python
  pass_filenames: true
  types: [file, markdown]
